(function(){
const C=window.BOTFORGE_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const api=(p,o={})=>fetch('/api'+p,{credentials:'include',headers:{'Content-Type':'application/json',...(o.headers||{})},...o}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d});
const toast=(m,t='info')=>{let b=$('#toast');if(!b){b=document.createElement('div');b.id='toast';document.body.appendChild(b)}const x=document.createElement('div');x.className='toast '+t;x.textContent=m;b.appendChild(x);setTimeout(()=>x.remove(),3600)};
const money=n=>`${C.currency||'KES'} ${Number(n||0).toLocaleString('en-KE',{minimumFractionDigits:2})}`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
window.BF={toast,money,api};
const savedTheme=localStorage.getItem('bf_theme');const theme=savedTheme||'light';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;
document.addEventListener('click',e=>{const t=e.target.closest('[data-theme]');if(t){const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;document.documentElement.style.colorScheme=n;localStorage.setItem('bf_theme',n);$('[data-theme]').forEach(b=>{b.innerHTML=themeIcon(n==='dark');b.setAttribute('aria-label',n==='dark'?'Switch to light mode':'Switch to dark mode');b.title=n==='dark'?'Switch to light mode':'Switch to dark mode'})}const m=e.target.closest('[data-menu]');if(m){document.body.classList.toggle('nav-open');m.setAttribute('aria-expanded',document.body.classList.contains('nav-open'))}if(e.target.closest('[data-close-nav]'))document.body.classList.remove('nav-open')});
const themeIcon=dark=>dark?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.7 6.7 0 0 0 21 12.8Z"/></svg>'; $('[data-theme]').forEach(b=>{b.innerHTML=themeIcon(theme==='dark');b.setAttribute('aria-label',theme==='dark'?'Switch to light mode':'Switch to dark mode');b.title=theme==='dark'?'Switch to light mode':'Switch to dark mode'});
const path=location.pathname.split('/').pop()||'index.html';$$('.side-link[href]').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});
$$('[data-logout],#logout').forEach(b=>b.addEventListener('click',async e=>{e.preventDefault();await fetch('/api/auth/logout',{method:'POST',credentials:'include'}).catch(()=>{});localStorage.removeItem('bf_user');location.href='login.html'}));
const grid=$('#botGrid');if(grid){grid.innerHTML=(C.bots||[]).map(b=>`<article class="card bot-card"><span class="status">Available</span><h3>${esc(b.name)}</h3><p>${esc(b.description)}</p><div class="card-meta"><strong>${money(b.price)}</strong><span>${esc(b.category)}</span></div><a class="btn" href="deploy.html?bot=${encodeURIComponent(b.id)}">View details</a></article>`).join('')||'<div class="empty"><h3>No bots available yet</h3></div>';$('#botSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('.bot-card').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q))})}
const params=new URLSearchParams(location.search),botId=params.get('bot'),bot=(C.bots||[]).find(b=>String(b.id)===botId);
if($('#botTitle')&&bot){$('#botTitle').textContent=bot.name;$('#botDesc').textContent=bot.description||'';if($('#botPrice'))$('#botPrice').textContent=money(bot.price)}
if($('#payNumber'))$('#payNumber').textContent=C.paymentNumber||'Payment provider not configured';
$$('.amount-btn').forEach(b=>b.addEventListener('click',()=>{if($('#amount'))$('#amount').value=b.dataset.amount}));
$('#payBtn')?.addEventListener('click',async()=>{const n=Number($('#amount')?.value);if(!Number.isFinite(n)||n<C.minDeposit||n>C.maxDeposit||n%50!==0)return toast(`Enter an amount from ${money(C.minDeposit)} to ${money(C.maxDeposit)} in KSh 50 steps.`,'warning');if(!$('#demoDeposit')?.checked)return toast('Real deposits require a verified payment provider/webhook.','warning');try{await api('/wallet/demo-credit',{method:'POST',body:JSON.stringify({amount:n})});toast('Demo deposit credited.','success');setTimeout(()=>location.reload(),400)}catch(e){toast(e.message,'warning')}});
$('#deployForm')?.addEventListener('submit',e=>{e.preventDefault();const session=$('#session')?.value.trim(),pkg=$('#package')?.value||'50-20';if(!/^[A-Za-z0-9:_./?=&+\-]{8,512}$/.test(session))return toast('Session ID/link must be 8–512 valid characters.','warning');const price=Number(bot?.price||String(pkg).split('-')[0]||0);localStorage.setItem('bf_pending_deploy',JSON.stringify({botId:botId||'bot',botName:bot?.name||'Bot',package:pkg,price,sessionMasked:session.slice(0,4)+'••••'+session.slice(-3),session}));location.href='payment.html?deploy=1'});
const pending=(()=>{try{return JSON.parse(localStorage.getItem('bf_pending_deploy')||'null')}catch{return null}})();if($('#pendingDeploy')&&pending){$('#pendingDeploy').classList.remove('hidden');$('#pendingDeploy').innerHTML=`<strong>${esc(pending.botName)}</strong><p>Package: ${esc(pending.package)}</p><p>Price: ${money(pending.price)}</p>`}
$('#confirmDemoDeploy')?.addEventListener('click',async()=>{if(!pending)return toast('No pending deployment.','warning');try{await api('/deployments',{method:'POST',body:JSON.stringify({botId:pending.botId,botName:pending.botName,packageName:pending.package,price:pending.price,session:pending.session})});localStorage.removeItem('bf_pending_deploy');toast('Deployment started.','success');setTimeout(()=>location.href='dashboard.html',500)}catch(e){toast(e.message,'warning')}});
async function hydrate(){try{const me=await api('/auth/me');localStorage.setItem('bf_user',JSON.stringify(me.user));if($('#userName'))$('#userName').textContent=me.user.name||me.user.email.split('@')[0];const d=await api('/me/state');if($('#walletBalance'))$('#walletBalance').textContent=money(d.wallet);if($('#activeBots'))$('#activeBots').textContent=(d.deployments||[]).filter(x=>['Running','Deploying'].includes(x.status)).length;if($('#notificationCount'))$('#notificationCount').textContent=(d.notifications||[]).filter(x=>!x.read).length;if($('#rewardPoints'))$('#rewardPoints').textContent=String(d.rewards?.points||0);
const deps=$('#deployments');if(deps)deps.innerHTML=d.deployments?.length?d.deployments.map(x=>`<article class="card"><div class="row-between"><span class="status ${x.status==='Running'?'':'off'}">${esc(x.status)}</span><span class="small">${esc(x.created)}</span></div><h3>${esc(x.bot)}</h3><p>Package: ${esc(x.package)}</p><p>Session: <code>${esc(x.sessionMasked||'protected')}</code></p><div class="hero-actions"><button class="btn ghost" data-deploy-action="stop" data-id="${x.id}">Stop</button><button class="btn ghost" data-deploy-action="restart" data-id="${x.id}">Restart</button><button class="btn danger" data-deploy-action="delete" data-id="${x.id}">Delete</button></div></article>`).join(''):'<div class="empty"><h3>No deployments yet</h3><p>Choose an available bot to start your first deployment.</p><a class="btn" href="bots.html">Browse bots</a></div>';
const ns=$('#notificationList');if(ns)ns.innerHTML=d.notifications?.length?d.notifications.map(x=>`<article class="card ${x.read?'':'unread'}"><div class="row-between"><strong>${esc(x.title)}</strong><span class="small">${esc(x.at)}</span></div><p>${esc(x.message)}</p><button class="btn ghost" data-read-notification="${x.id}" ${x.read?'disabled':''}>${x.read?'Read':'Mark as read'}</button></article>`).join(''):'<div class="empty"><h3>You are all caught up</h3></div>';
}catch(e){if(location.pathname.includes('dashboard')||location.pathname.includes('payment')||location.pathname.includes('deploy')||location.pathname.includes('notifications'))toast(e.message,'warning')}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-deploy-action]');if(b){try{await api('/deployments/'+encodeURIComponent(b.dataset.id)+'/action',{method:'POST',body:JSON.stringify({action:b.dataset.deployAction})});location.reload()}catch(x){toast(x.message,'warning')}}const n=e.target.closest('[data-read-notification]');if(n){try{await api('/me/notifications/'+encodeURIComponent(n.dataset.readNotification)+'/read',{method:'POST'});location.reload()}catch(x){toast(x.message,'warning')}}});
$('#markRead')?.addEventListener('click',async()=>{const cards=$$('#notificationList [data-read-notification]');for(const b of cards){if(!b.disabled)await api('/me/notifications/'+encodeURIComponent(b.dataset.readNotification)+'/read',{method:'POST'}).catch(()=>{})}location.reload()});
const date=$('#currentDate');if(date)date.textContent=new Intl.DateTimeFormat('en-US',{dateStyle:'full'}).format(new Date());const time=$('#currentTime');if(time){const tick=()=>time.textContent=new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date());tick();setInterval(tick,30000)}
hydrate();
})();