(function(){
  const $=s=>document.querySelector(s), toast=m=>{let b=$('#toast');if(!b){b=document.createElement('div');b.id='toast';document.body.appendChild(b)}const x=document.createElement('div');x.className='toast warning';x.textContent=m;b.appendChild(x);setTimeout(()=>x.remove(),3500)};
  const theme=localStorage.getItem('bf_theme')||'light';document.documentElement.dataset.theme=theme;document.addEventListener('click',e=>{const t=e.target.closest('[data-theme]');if(!t)return;const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('bf_theme',n);t.textContent=n==='dark'?'☀':'☾'});
  const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
  const register=$('#registerForm');if(register)register.addEventListener('submit',e=>{e.preventDefault();const name=$('#name').value.trim(),username=$('#username')?.value.trim()||'',email=$('#email').value.trim().toLowerCase(),phone=$('#phone')?.value.trim()||'',password=$('#password').value,confirm=$('#confirmPassword')?.value||password;if(name.length<2)return toast('Enter your full name.');if(!validEmail(email))return toast('Enter a valid email address.');if(password.length<8)return toast('Use at least 8 characters for your password.');if(password!==confirm)return toast('Passwords do not match.');if(!$('#terms')?.checked)return toast('Accept the terms and privacy policy to continue.');
    // Demo-only session: no password is persisted. Production auth must be server-side.
    const u={id:'demo_'+Date.now(),name,username,email,phone,role:'user',created:new Date().toISOString()};localStorage.setItem('bf_user',JSON.stringify(u));localStorage.setItem('bf_state',JSON.stringify({wallet:0,notifications:[{title:'Welcome to BFBotForge Cyp',message:'Your account is ready. Connect a secure backend before real payments or deployments.',at:new Date().toLocaleString(),read:false}],deployments:[],transactions:[]}));location.href='dashboard.html';
  });
  const login=$('#loginForm');if(login)login.addEventListener('submit',e=>{e.preventDefault();const email=$('#email').value.trim().toLowerCase();if(!validEmail(email))return toast('Enter a valid email address.');const stored=(()=>{try{return JSON.parse(localStorage.getItem('bf_user')||'null')}catch{return null}})();if(!stored||stored.email!==email)return toast('No demo session matches this email. For production, connect the form to your secure authentication API.');localStorage.setItem('bf_user',JSON.stringify(stored));location.href='dashboard.html'});
  $('#githubBtn')?.addEventListener('click',()=>toast('OAuth is intentionally disabled until a secure server-side provider is configured.'));
})();
